export default defineAppConfig({
  pages: [
    "pages/index/index",
    "pages/all-games/index",
    "pages/game-gauntlet/index",
    "pages/memory-challenge/index",
    "pages/memory-challenge/play",
    "pages/memory-challenge/result",
    "pages/rock-paper-scissors/index",
    "pages/rock-paper-scissors/play",
    "pages/rock-paper-scissors/result",
    "pages/mental-math/index",
    "pages/mental-math/play",
    "pages/mental-math/result",
    "pages/twenty-four/index",
    "pages/twenty-four/play",
    "pages/twenty-four/result",
    "pages/digit-span/index",
    "pages/digit-span/play",
    "pages/digit-span/result",
    "pages/multiple-object-tracking/index",
    "pages/pattern-completion/index",
    "pages/pattern-completion/play",
    "pages/pattern-completion/result",
    "pages/number-order/index",
    "pages/head-count/index",
    "pages/word-scramble/index",
    "pages/bird-count/index",
    "pages/bird-count/play",
    "pages/bird-count/result",
    "pages/color-trap/index",
    "pages/spatial-rotation/index",
    "pages/hidato/index",
    "pages/hidato/play",
    "pages/hidato/result",
    "pages/tents-camp/index",
    "pages/tents-camp/play",
    "pages/tents-camp/result",
    "pages/sumplete-grid/index",
    "pages/traffic-escape/index",
    "pages/traffic-escape/play",
    "pages/traffic-escape/result",
    "pages/music-theory/index",
    "pages/music-theory/play",
    "pages/music-theory/result",
    "pages/netwalk/index",
    "pages/netwalk/play",
    "pages/netwalk/result",
    "pages/loop-line/index",
    "pages/loop-line/play",
    "pages/loop-line/result",
    "pages/pet/index",
    "pages/settings/index",
    "pages/training-records/index",
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#fff",
    navigationBarTitleText: "Cici的脑部锻炼",
    navigationBarTextStyle: "black",
    enablePullDownRefresh: false,
  },
  lazyCodeLoading: "requiredComponents",
  sitemapLocation: "sitemap.json",
});
